image: python:3.10-alpine

before_script:
  - python --version
  - pip install pylint==2.14.3
  - pylint --version
  - touch temp.txt



stages:
  - lint
  - display-lint

lint:
  stage: lint
  script:
    - pylint worker/ >> temp.txt
    - pylint web/ >> temp.txt
    artifacts:
        paths:
          - temp.txt

display-lint:
  stage: display-lint
  script:
    - cat temp.txt
    - rm -f temp.txt
  dependencies:
    - lint