image: python:3.10-alpine

before_script:
  - pip install pylint==2.14.3
  - touch temp.txt

lint:
  stage: lint
  script:
    - pylint worker/ >> temp.txt
    - pylint web/ >> temp.txt
  artifacts:
        paths:
          - temp.txt

display-lint:
  stage: display-lint
  script:
    - cat temp.txt
    - rm -f temp.txt

stages:
  - lint
  - display-lint
