version: '3'

services:
  nginx:
    container_name: nginx
    hostname: nginx
    image: zarak.fr:8092/cache/library/nginx:1.22-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - worker
    networks:
      - back
      - front

  web:
    container_name: web
    hostname: web
    build: web
    restart: always
    networks:
      - front
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 100M
  
  worker:
    container_name: worker
    hostname: worker
    build: worker
    restart: always
    networks:
      - back
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 100M

  redis:
    image: zarak.fr:8092/cache/library/redis:7.0.1-alpine
    container_name: redis
    hostname: redis
    restart: always
    volumes:
      - ./redis-persistence:/redis/data
    networks:
      - back
    deploy:
      resources:
        limits:
          memory: 100M

networks:
  front:
  back:
